"""One-off migration: single-tenant schema -> multi-tenant.

Adds the ``tenants`` table, creates a first tenant, and backfills ``tenant_id``
onto every content table so existing rows keep working. Safe to run once;
re-running is refused because ``tenants`` already exists.

    python migrate_multitenant.py
    python migrate_multitenant.py --name "Kaushik Bhat" --slug kaushik-bhat

Take a database backup first — this rewrites constraints on live tables.
"""

from __future__ import annotations

import argparse
import asyncio
import logging

from sqlalchemy import text

from app.core.security import new_admin_key, new_site_key
from app.db.session import dispose_engine, engine
from app.models.tenant import Tenant

logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")
logger = logging.getLogger("migrate")

# Every table that becomes tenant-scoped.
CONTENT_TABLES = (
    "site_profile",
    "page_content",
    "photos",
    "videos",
    "faqs",
    "enquiries",
)


async def _table_exists(conn, table: str) -> bool:
    return bool(
        await conn.scalar(text("SELECT to_regclass(:name)"), {"name": f"public.{table}"})
    )


async def run(*, name: str, slug: str) -> None:
    async with engine.begin() as conn:
        if await _table_exists(conn, "tenants"):
            logger.error("tenants table already exists — migration already applied")
            return

        missing = [t for t in CONTENT_TABLES if not await _table_exists(conn, t)]
        if missing:
            logger.error(
                "Missing tables %s — run `python seed.py` first to create the schema",
                ", ".join(missing),
            )
            return

        logger.info("Creating tenants table")
        await conn.run_sync(Tenant.__table__.create)

        site_key = new_site_key()
        admin_key = new_admin_key()
        tenant_id = await conn.scalar(
            text(
                "INSERT INTO tenants (name, slug, site_key, admin_key, is_active) "
                "VALUES (:name, :slug, :site_key, :admin_key, true) RETURNING id"
            ),
            {"name": name, "slug": slug, "site_key": site_key, "admin_key": admin_key},
        )
        logger.info("Created tenant %s (%s)", name, tenant_id)

        for table in CONTENT_TABLES:
            await conn.execute(
                text(f"ALTER TABLE {table} ADD COLUMN tenant_id UUID")  # noqa: S608
            )
            rows = (
                await conn.execute(
                    text(f"UPDATE {table} SET tenant_id = :tid"),  # noqa: S608
                    {"tid": tenant_id},
                )
            ).rowcount
            await conn.execute(
                text(f"ALTER TABLE {table} ALTER COLUMN tenant_id SET NOT NULL")
            )
            await conn.execute(
                text(
                    f"ALTER TABLE {table} ADD CONSTRAINT fk_{table}_tenant_id_tenants "
                    "FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE"
                )
            )
            await conn.execute(
                text(f"CREATE INDEX ix_{table}_tenant_id ON {table} (tenant_id)")
            )
            logger.info("%-14s tenant_id added, %d row(s) backfilled", table, rows)

        # site_profile stops being a hard singleton; one row per tenant instead.
        await conn.execute(
            text("ALTER TABLE site_profile DROP CONSTRAINT IF EXISTS ck_site_profile_singleton")
        )
        await conn.execute(
            text(
                "ALTER TABLE site_profile "
                "ADD CONSTRAINT uq_site_profile_tenant_id UNIQUE (tenant_id)"
            )
        )
        # The old pk was written client-side as a literal 1, so there is no
        # sequence behind it; new tenants need one to get their own profile row.
        await conn.execute(text("ALTER TABLE site_profile ALTER COLUMN id DROP DEFAULT"))
        await conn.execute(
            text("ALTER TABLE site_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
        )
        await conn.execute(
            text(
                "SELECT setval(pg_get_serial_sequence('site_profile', 'id'), "
                "COALESCE((SELECT MAX(id) FROM site_profile), 1))"
            )
        )
        logger.info("site_profile   singleton check dropped, id is now an identity column")

        # A slug / youtube id only has to be unique within one tenant.
        for table, column in (("page_content", "slug"), ("videos", "youtube_id")):
            await conn.execute(text(f"DROP INDEX IF EXISTS ix_{table}_{column}"))
            await conn.execute(
                text(f"CREATE INDEX ix_{table}_{column} ON {table} ({column})")
            )
            await conn.execute(
                text(
                    f"ALTER TABLE {table} "
                    f"ADD CONSTRAINT uq_{table}_tenant_id_{column} UNIQUE (tenant_id, {column})"
                )
            )
            logger.info("%-14s %s is now unique per tenant", table, column)

    await dispose_engine()

    print("\n" + "=" * 68)
    print(f"  Tenant created: {name}")
    print(f"  slug       {slug}")
    print(f"  site_key   {site_key}")
    print(f"  admin_key  {admin_key}")
    print("=" * 68)
    print("  Save the admin_key now — it is never shown again.")
    print("  Rotate with POST /api/tenants/{id}/rotate-keys if you lose it.\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--name", default="Kaushik Bhat", help="Display name")
    parser.add_argument("--slug", default="kaushik-bhat", help="URL/storage-safe id")
    args = parser.parse_args()

    asyncio.run(run(name=args.name, slug=args.slug))


if __name__ == "__main__":
    main()
